### ISSUE TITLE
Interactive region selection with vitessceR giottoToAnndataZarr() error

### ISSUE THREAD

**Issue by ariel-lli** [giotto-suite/Giotto#1213]
Hello, 

I encountered the following error and warning when running giottoToAnndataZarr().
giottoToAnndataZarr(gobject= SLE,
                    spat_unit = "cell",
                    feat_type = "rna",
                    output_path = "SLE_anndata_zarr",
                    expression = "normalized")
SLE is a regular Giotto object from MERFISH dataset. It contains the count matrix, spatial information, metadata  and other downstream analysis data.

<img width="711" height="134" alt="Image" src="https://github.com/user-attachments/assets/6e4abbbe-ba05-4c02-b911-19eb8c092c9d" />
<img width="711" height="240" alt="Image" src="https://github.com/user-attachments/assets/a66febc8-1ca9-459c-854e-7d9ebb311cfa" />
My python path is "/home/yul153/.conda/envs/giotto_env/bin/python". I am not sure if the python path was the problem. The code took forever to run, so I had to manually stop it, which gave me the object "Exp" not found error. 
Please provide any insight. Thank you!

**Comment by RubD** [comment]
@sjcshin is this something you have encountered before?

**Comment by ariel-lli** [comment]
Here is my sessioninfo 

<img width="725" height="623" alt="Image" src="https://github.com/user-attachments/assets/77d31799-ec62-4880-9c5a-e61f00692076" />

I tried to download GiottoData to test on an existing object, but I encountered an error when I ran remotes::install_github("drieslab/GiottoData").

<img width="750" height="96" alt="Image" src="https://github.com/user-attachments/assets/e85e91a0-2d37-4f68-89b0-2a2bfd7e2b02" />

**Comment by josschavezf** [comment]
Hi @ariel-lli, thanks a lot for sharing this issue. I was able to reproduce it. The error comes from a recent update in the basilisk  R package which changed the way they connect internally with Python. I need to update our function to be compatible with the recent changes. Let me work on this and I'll come back to you asap.

**Comment by josschavezf** [comment]
Hi @ariel-lli, I have updated the code in the Giotto repository to fix this issue. 

Please install the development branch by running:

remotes::install_github("drieslab/Giotto@suite_dev")

The first time you run giottoToAnndataZarr, a basilisk (python) virtual environment will be created. This installation will take a couple of minutes, but the environment will be automatically detected afterwards when running the function again.

**Comment by ariel-lli** [comment]
Hi, thanks so much for your help. I encountered the same issue as mentioned above, when I tried to install (remotes::install_github("drieslab/Giotto@suite_dev")). I am running R studio DEI on a server

> 
> <img alt="Image" width="750" height="96" src="https://private-user-images.githubusercontent.com/245094237/517063210-e85e91a0-2d37-4f68-89b0-2a2bfd7e2b02.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM3NTkzNTUsIm5iZiI6MTc2Mzc1OTA1NSwicGF0aCI6Ii8yNDUwOTQyMzcvNTE3MDYzMjEwLWU4NWU5MWEwLTJkMzctNGY2OC04OWIwLTJhMmJmZDdlMmIwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEyMVQyMTA0MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODBlODcxMzZiMTA5NDc1NzlmNTcxMWZmMzU4MGE0ZWFlNGYyZDEwOTU4ZmQzZDQ2NjM4Mzg5MDZlYzg3NDk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Vys4oj7BttDDRXTi99QH-XNUJq4r5OUtaZZxnxziwxI">

**Comment by josschavezf** [comment]
@ariel-lli  Oh, I see. Unfortunately installing terra in the server tends to cause troubles. In my experience when working in the server, two things have helped: 1) Install the dependencies using R in the terminal before launching RStudio. 2) It's also possible that you need to load additional modules before installing terra. I encountered this same issue while ago and had to load something like this in the server: ml R/4.4.1 udunits sqlite3/3.35.5. I hope it helps.

**Comment by ariel-lli** [comment]
Dear Giotto developers,

Thanks so much for your help. I installed the developer version of Giotto, but I am still getting the same error. I assumed that this command should be run before initiating the vc configuration, but even when I tried to initiate using vc <- VitessceConfig$new(schema_version = "1.0.16", name = "RNAscope Config"), it still give me the save error. Do you think that there is a problem with my Python environment?  

<img width="738" height="209" alt="Image" src="https://github.com/user-attachments/assets/b9662210-25f1-4e43-9823-94b3e70593b2" />

<img width="547" height="108" alt="Image" src="https://github.com/user-attachments/assets/404c78b2-194a-4a3e-a315-962e5f75713b" />
